### ISSUE TITLE
How to submit my result?

### ISSUE THREAD

**Issue by zhufeng888** [MCG-NJU/MultiSports#2]
the competition page describes:The Development Leaderboard is based on a fixed random subset of 50% of the test dataset. To submit, upload a .zip file containing a test_result.json file with the prediction.
but the github provides a submission_example.zip containing *.pkl file . When I try to directly submit your submission_example.zip, I dont't get SCORE and STATUS is Failed as follows:
`Error:
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.   

Traceback (most recent call last):
  File "/tmp/codalab/tmp8rnAuQ/run/program/evaluate.py", line 26, in 
    submission_answer = open(submission_answer_file).read()
IOError: [Errno 2] No such file or directory: '/tmp/codalab/tmp8rnAuQ/run/input/res/answer.txt'`

**Comment by zhufeng888** [comment]
A serious problem I met is that the size of the frame_detections.pkl generated by MOC-Dtector on test dataset is over 12G. is this normal?(It seems I could not upload so big file ). I also evaluate the val datasets with the same partly training model and get a 0.09 score on Frame-MAP, so it is strange when I use test datasets. Hope to have your advice. Thanks!

**Comment by yixuanli98** [comment]
Please make sure you submit in the test version competition, which is a [https://competitions.codalab.org/competitions/33355](https://competitions.codalab.org/competitions/33355).

**Comment by yixuanli98** [comment]
The results of MOC are actually very large and my frame_detections.pkl is 8.2G for test set. Maybe you can have a try on SlowFast or design some strategies to reduce the MOC results.

**Comment by zhufeng888** [comment]
> The results of MOC are actually very large and my frame_detections.pkl is 8.2G for test set. Maybe you can have a try on SlowFast or design some strategies to reduce the MOC results.

Thank you very much, your advice gives me a great help and I have completely gone through the process, though my score is 0.0. I'm trying to find the issue. while I have a question. The experiment results showed in the bottom of the web https://deeperaction.github.io/multisports/  is evaluated in val sets but not in random 50% test sets, right?

**Comment by yixuanli98** [comment]
Yes, the results in our paper are evaluated on the val set.

**Comment by zhufeng888** [comment]
> Yes, the results in our paper are evaluated on the val set.

Thank you! Wish you a happy day!
