### ISSUE TITLE
How did you implement SlowFast Det?

### ISSUE THREAD

**Issue by Tsunehiko** [MCG-NJU/MultiSports#22]
Thank you for your excellent work! I've read your paper, and I have a question about the implementation of SlowFast Det. The original SlowFast paper mentions SlowFast Det for AVA dataset, but it does not describe a model that supports datasets like MultiSports, where bounding boxes are annotated on all frames. How did you implement SlowFast Det? (More specifically, did you apply Faster R-CNN only to the keyframes? How do you output bounding boxes for the remaining frames?)

**Comment by yixuanli98** [comment]
We apply Faster R-CNN to all the frames and SlowFast network will predict action categories for the detected boxes of all the frames.

**Comment by Tsunehiko** [comment]
Thank you for your response. How do you use the features of the SlowFast network with RoI Align? I am curious about how to handle features of different sizes, as there may or may not be Slow Path features depending on the frame

**Comment by yixuanli98** [comment]
Sorry for the late reply. For each frame, we input 64 frames around it and output the result of that frame. We get the ROI features according to the key frame's box as the original SlowFast Det.

**Comment by tsunehiko** [comment]
Thank you for your response, it is very helpful!
Is this the correct understanding? You input the set of 64 frames by shifting one frame at a time. In each set, you obtain the RoI feature using the detection results of the key frame (the center frame of the 64 frames).

**Comment by yixuanli98** [comment]
Yes, that's it.
