### ISSUE TITLE
请问训练的原始数据集能提供吗

### ISSUE THREAD

**Issue by Lzx1433** [MCG-NJU/MultiSports#4]

**Comment by yixuanli98** [comment]
Please register in our competition to get the data.

**Comment by Lzx1433** [comment]
您好，我已注册并参赛，我已下载了您提供的网盘文件，为何缺少multisports_half_test_GT.pkl文件，只存在multisports_half_test.pkl文件，请问前者是需要自己生成的吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCG-NJU/MultiSports"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 中午12:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MCG-NJU/MultiSports] 请问训练的原始数据集能提供吗 (#4)





 
Please register in our competition to get the data.

**Comment by yixuanli98** [comment]
multisports_half_test_GT.pkl is the test set GT. We will not release it.

**Comment by yixuanli98** [comment]
I think you may have some misunderstanding about our file hierarchy. The multisports_half_test_GT.pkl file is the test set ground-truth therefore it will not be released until the challenge ends. The multisports_half_test.pkl is a list of video name in which the prediction of these videos should be included in the submission file. For more details, please refer to the official website of competition.

**Comment by Lzx1433** [comment]
好的明白了，谢谢您的回复与解释，十分感谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCG-NJU/MultiSports"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月26日(星期一) 下午3:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MCG-NJU/MultiSports] 请问训练的原始数据集能提供吗 (#4)





 
I think you may have some misunderstanding about our file hierarchy. The multisports_half_test_GT.pkl file is the test set ground-truth therefore it will not be released until the challenge ends. The multisports_half_test.pkl is a list of video name in which the prediction of these videos should be included in the submission file. For more details, please refer to the official website of competition.
