### ISSUE TITLE
可以详细说下如何复现slowfast结果吗

### ISSUE THREAD

**Issue by ckx506772099** [MCG-NJU/MultiSports#7]
您好，可以详细说下如何复现slowfast结果吗，我尝试按照论文复现slowfast结果，但是无法达到论文效果，请问论文中是如何进行inference的，另外训练时loss和top-1 acc是多少

**Comment by yixuanli98** [comment]
We use the code in the mmaction2 and provide the details in the paper's supplementary material. We have provided the person boxes we generated. Maybe you can have a try with them.

**Comment by yixuanli98** [comment]
We modify the dataset part in order to adapt to the dense annotations.

**Comment by ckx506772099** [comment]
Thanks for your reply. I modified the dataset part of Slowfast, and modified the configuration file and trained the model according to the instructions in the paper. Then use the same link algorithm as MOC and the person boxes your provided for inference, but the results obtained were very low.
I suspect the problem may lie in two ways
1. My usage of the link algorithm is wrong.
2. The problem of my model is that the top1 of my basic Slowfast model is low, but the top1 has been greatly improved after I made some changes, but the inference result is still very low.
So I would like to ask you some questions:
1. In the inference phase, how did you make it
2. What is the top1 of your slowfast model
3. How is your dataset modified







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCG-NJU/MultiSports"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 中午1:01
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MCG-NJU/MultiSports] 可以详细说下如何复现slowfast结果吗 (#7)





 
We modify the dataset part in order to adapt to the dense annotations.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yixuanli98** [comment]
What's your frame mAP? This has nothing to do with the linking algorithm.
1. In the inference time, I predicts action category for every detected person box.
2. I'm sorry that we do not record the top1 value.
3. I don't think this is a problem as long as you can train your model with normal loss. If your loss can not decrease, maybe there are some bugs in your code, such as the input format of GT and proposals. One bug I ever had is the wrong format of the proposal format, which led to the [0, 0 ,1, 1] proposal for all images.

**Comment by ckx506772099** [comment]
I am calculating the frame mAP, can I get the code of link algorithm or know the detailed steps of link algorithm?&nbsp;
I tried to use the link algorithm of MOC in the result of every detected person box, and K == 1, but the effect was not very ideal
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCG-NJU/MultiSports"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月3日(星期五) 下午4:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MCG-NJU/MultiSports] 可以详细说下如何复现slowfast结果吗 (#7)





 
What's your frame mAP? This has nothing to do with the linking algorithm.
  
In the inference time, I predicts action category for every detected person box.
 
I'm sorry that we do not record the top1 value.
 
I don't think this is a problem as long as you can train your model with normal loss. If your loss can not decrease, maybe there are some bugs in your code, such as the input format of GT and proposals. One bug I ever had is the wrong format of the proposal format, which led to the [0, 0 ,1, 1] proposal for all images.
  
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yixuanli98** [comment]
We just use the link code from MOC without change. Please make sure every predicted person box has only one category.

**Comment by ckx506772099** [comment]
How is the link algorithm k set, when used to process slowfast's results


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MCG-NJU/MultiSports"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月4日(星期六) 凌晨0:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MCG-NJU/MultiSports] 可以详细说下如何复现slowfast结果吗 (#7)





 
We just use the link code from MOC without change. Please make sure every predicted person box has only one category.
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yixuanli98** [comment]
K=1
